version: "3.8"

services:
  peer0.org1.example.com:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.org1.example.com
    environment:
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      - FABRIC_LOGGING_SPEC=DEBUG
    ports:
      - "7051:7051"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
