FROM python:3.11-slim

WORKDIR /app
COPY pyproject.toml .
RUN pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple -e ".[web]" \
    && pip install --no-cache-dir -i https://pypi.tuna.tsinghua.edu.cn/simple uvicorn
COPY blocksec/ ./blocksec/
COPY labs/ ./labs/

EXPOSE 8000
CMD ["uvicorn", "blocksec.web.server:app", "--host", "0.0.0.0", "--port", "8000"]
